version: "3.8"
name: itsg
services:
  arangodb:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: test123
    ports:
      - 8529:8529
  populate-arangodb:
    image: arangodb:3.11
    command: [
      "sh", "-c",
      # retry `arangoimport` five times at 4 second intervals, to give 
      # the arangodb container time to prepare for connectons.
      # TODO: should be able to do this cleaner with a health/readiness
      # check on the arangodb container, but couldn't seem to write one 
      "for i in 1 2 3 4 5; \
      do \
      arangoimport \
      --server.endpoint http+tcp://arangodb:8529 \
      --server.username root \
      --server.password test123 \
      --server.database itsg33 \
      --create-database true \
      --file etc/controls.json \
      --collection controls \
      --create-collection true \
      --overwrite true \
      && break \
      || sleep 4; \
      done"
    ]
    volumes:
        - ./controls.json:/etc/controls.json
    depends_on:
      arangodb:
        condition: service_started
  api:
    build: ./api
    image: api:1
    environment:
      DB_URL: http://arangodb:8529
      DB_NAME: itsg33
      DB_USER: root
      DB_PASS: test123
      PORT: 4000
      DEBUG_PORT: 9229
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./api:/home/api
    depends_on:
      populate-arangodb:
        condition: service_completed_successfully
  ui:
    build: ./ui
    image: ui:1
    environment:
      BROWSER: none
      PORT: 3000
      API_PORT: 4000
    ports:
      - 3000:3000
    volumes:
      - ./ui:/home/ui
    depends_on:
      api:
        condition: service_started
    
    
    
