version: "3.8"
services:
  arangodb:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: test123
    ports:
      - 8529:8529
  ui:
    build: ui
    ports:
      - 8080:8080
  api:
    build: api
    environment:
      DB_URL: http://127.0.0.1:8529
      DB_NAME: itsg33
      DB_USER: root
      DB_PASS: test123
      PORT: 4000
    ports:
      - 4000:4000
    
    
    
    
