version: "3.8"
name: itsg
services:
  # proxies localhost:3000 to containers based on rules in envoy.yaml
  envoy:
    image: envoyproxy/envoy-distroless-dev
    entrypoint: envoy
    command: [ "-l", "warn", "-c", "/etc/envoy.yaml", "--service-cluster", "envoy"]
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml # Envoy configuration
    expose:
      - "3000" # Forward to proxied apps
      - "3001" # Envoy admin page
    ports:
      - "3000:3000"
      - "3001:3001"
  arangodb:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: test123
    ports:
      - 8529:8529
  ui:
    image: node:alpine
    working_dir: /home/node/ui
    entrypoint: npm
    command: ["run", "start"]
    ports:
      - 3000
    environment:
      BROWSER: none
    volumes:
    - type: bind
      source: ./ui
      target: /home/node/ui
  api:
    build: api
    # Auto reload when files change with watch mode
    command: node --watch index.js
    environment:
      DB_URL: http://arangodb:8529
      DB_NAME: itsg33
      DB_USER: root
      DB_PASS: test123
      PORT: 4000
    ports:
      - 4000
    volumes:
    - type: bind
      source: ./api
      target: /api
    
    
    
    
