version: "3.8"
services:
  arangodb:
    image: arangodb:3.11
    environment:
      - ARANGO_ROOT_PASSWORD: test123
    ports:
      - 8529:8529
  ui:
    build: ui
    ports:
      - 8080:8080
    
    
